# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hw < Formula
  desc "Friendly software that offers a friendly greeting.  Friendlyly."
  homepage "https://github.com/ariehm/helloworld"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ariehm/helloworld/releases/download/v0.0.9/helloworld_Darwin_x86_64.tar.gz"
      sha256 "d3bc7b9278c54b02b881d227beb7579a408b74c9d4f49cfcff8436b0e59a3eba"

      def install
        bin.install "hw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ariehm/helloworld/releases/download/v0.0.9/helloworld_Darwin_arm64.tar.gz"
      sha256 "df40dfd68b844bb6dd47d88d8af07bd893746e40d3420fc215985e56a39c9ce9"

      def install
        bin.install "hw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariehm/helloworld/releases/download/v0.0.9/helloworld_Linux_arm64.tar.gz"
      sha256 "e8b6ef104981cb5170240d228bc27356da037343122e8c93c1fb5d0f4e98a49e"

      def install
        bin.install "hw"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ariehm/helloworld/releases/download/v0.0.9/helloworld_Linux_x86_64.tar.gz"
      sha256 "3af93ad711ec190d7b17ad9ee5fe489bb8c69698434207bf274d502ac318273e"

      def install
        bin.install "hw"
      end
    end
  end

  def caveats
    <<~EOS
      Beware!  DOOM!
    EOS
  end

  test do
    system "#{bin}/hw"
  end
end
